#!/bin/bash
uniqpeers=$(ss | grep ssh | awk '{ print $6 }' | grep -v 10.51.00.)
discbin='/home/blueteam/discbin/discbin'

if [ -n "$uniqpeers" ]; then
        echo Suspicious SSH login detected on $(hostname) from $uniqpeers. | $discbin 'https://discord.com/api/webhooks/example' >/dev/null 2>&1 &
fi
