#!/bin/bash
uniqpeers=$(ss | grep ssh | awk '{ print $6 }' | grep -v 10.51.00.)
webhookurl=[url goes here]

if [ -n "$uniqpeers" ]; then
        echo Suspicious SSH login detected on $(hostname) from $uniqpeers. | /home/blueteam/discbin/discbin $webhookurl
